<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head runat="server">
<title>!zenuT</title>
</head>
<body>
<div id="header">!zenuT</div>
<div id="menu">
<a href="./">Home</a><br/>
<a href="queue">Queue</a><br/>
<a href="playlist">Playlist</a><br/>
<a href="search">Search</a><br/>
</div>
